### ISSUE TITLE
Update to the latest js-ipfs 

### ISSUE THREAD

**Issue by lidel** [ipfs-inactive/old-js-ipfs-website#307]
The website runs an ancient version of js-ipfs which still uses secio: 

> If you are running IPFS nodes with a diverse range of versions you'll want to upgrade them all to go-IPFS@0.6.0 or later and js-IPFS@0.47.0 at a minimum, otherwise you will start to lose connectivity with the rest of the network as SECIO ceases to be supported by peers.
> –  https://blog.ipfs.io/2020-10-29-js-ipfs-0-50/

## TODO

- [ ] switch from `ipfs` to the latest [`ipfs-core`](https://www.npmjs.com/package/ipfs-core) 
- [ ] make sure examples on the page work as expected
- [ ] fix service worker demo

**Comment by juliangruber** [comment]
I just ran into this, the first example should look something like:

```js
import * as IPFS from 'ipfs-core'

const node = await IPFS.create()
const data = 'Hello World!'
const results = await node.add(data)
console.log(results.cid.toString())
```

I wanted to craft a proper PR but then ran into https://github.com/ipfs/js.ipfs.io/issues/310.
